import React, { createContext, useContext, useMemo, useState } from 'react';
import { seedState } from '../data/seed';
import { generateMockPlan } from '../services/aiService';
import { createRecurringInstance } from '../utils/recurrence';
import type { AIPlan, LifeOSState, RecurringTask, Task } from '../types';
type LifeOSStore = { state: LifeOSState; isGenerating: boolean; toggleTask: (id: string) => void; generatePlan: (input: string) => Promise<void>; applyPlan: (plan: AIPlan) => void; clearPlan: () => void };
const Context = createContext<LifeOSStore | null>(null);
export function LifeOSProvider({ children }: { children: React.ReactNode }) { const [state, setState] = useState(seedState); const [isGenerating, setGenerating] = useState(false); const toggleTask = (id: string) => setState((current) => ({ ...current, tasks: current.tasks.map((task) => task.id === id ? { ...task, status: task.status === 'done' ? 'todo' : 'done' } : task) })); const generatePlan = async (input: string) => { setGenerating(true); const plan = await generateMockPlan(input); setState((current) => ({ ...current, lastAIPlan: plan })); setGenerating(false); }; const applyPlan = (plan: AIPlan) => setState((current) => { const today = new Date().toISOString().slice(0, 10); const existing = [...current.tasks]; const recurring = [...current.recurringTasks]; plan.actions.filter((action) => action.tool === 'createTask').forEach((action) => { const match = existing.find((task) => task.title === action.title && task.dueDate === today); if (match) { match.time = action.time; match.kind = 'ai-generated'; match.sourceActionId = action.id; } else { existing.push({ id: `task-${plan.id}-${action.id}`, title: action.title, time: action.time, dueDate: today, status: 'todo', kind: 'ai-generated', category: action.category, sourceActionId: action.id }); } }); plan.actions.filter((action) => action.tool === 'createRecurringTask').forEach((action) => { if (!recurring.some((task) => task.title === action.title)) { const item: RecurringTask = { id: `rec-${plan.id}-${action.id}`, title: action.title, schedule: action.title === '交房租' ? 'monthly' : 'weekly', scheduleLabel: action.title === '交房租' ? '每月 1 日' : '每周六', time: action.time ?? '10:00', nextRun: today, enabled: true }; recurring.push(item); existing.push(createRecurringInstance(item)); } }); return { ...current, tasks: existing, recurringTasks: recurring, lastAIPlan: undefined }; }); const value = useMemo(() => ({ state, isGenerating, toggleTask, generatePlan, applyPlan, clearPlan: () => setState((current) => ({ ...current, lastAIPlan: undefined })) }), [state, isGenerating]); return <Context.Provider value={value}>{children}</Context.Provider>; }
export function useLifeOS() { const value = useContext(Context); if (!value) throw new Error('useLifeOS must be used inside LifeOSProvider'); return value; }
