import React from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { IconName, Tab } from '../types';
export const colors = { bg: '#F6F7FB', ink: '#172033', muted: '#8D96A8', line: '#E9ECF3', purple: '#7764EE', purpleSoft: '#F0EEFF', white: '#FFFFFF', success: '#2EB875', warning: '#FFAA48' };
export const shadow = { shadowColor: '#78829B', shadowOpacity: 0.08, shadowRadius: 15, shadowOffset: { width: 0, height: 5 }, elevation: 2 };
export function Screen({ children }: { children: React.ReactNode }) { return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>{children}</ScrollView></SafeAreaView>; }
export function Header({ title, subtitle, icon = 'ellipsis-horizontal' as IconName }: { title: string; subtitle?: string; icon?: IconName }) { return <View style={styles.header}><View><Text style={styles.title}>{title}</Text>{subtitle && <Text style={styles.subtitle}>{subtitle}</Text>}</View><Pressable style={styles.headerButton} accessibilityLabel="页面操作"><Ionicons name={icon} size={20} color={colors.ink} /></Pressable></View>; }
export function Card({ children, style }: { children: React.ReactNode; style?: object }) { return <View style={[styles.card, style]}>{children}</View>; }
export function SectionHeader({ title, action }: { title: string; action?: string }) { return <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{title}</Text>{action && <Text style={styles.action}>{action}  ›</Text>}</View>; }
export function Segment({ values, active, onChange }: { values: string[]; active: number; onChange?: (index: number) => void }) { return <View style={styles.segment}>{values.map((value, index) => <Pressable key={value} onPress={() => onChange?.(index)} style={[styles.segmentItem, active === index && styles.segmentItemActive]}><Text style={[styles.segmentText, active === index && styles.segmentTextActive]}>{value}</Text></Pressable>)}</View>; }
export function BottomNav({ active, onChange }: { active: Tab; onChange: (tab: Tab) => void }) { const items: { key: Tab; label: string; icon: IconName; activeIcon: IconName }[] = [{ key: 'today', label: '今天', icon: 'home-outline', activeIcon: 'home' }, { key: 'timeline', label: '时间轴', icon: 'calendar-outline', activeIcon: 'calendar' }, { key: 'notes', label: '笔记', icon: 'document-text-outline', activeIcon: 'document-text' }, { key: 'fitness', label: '健身', icon: 'fitness-outline', activeIcon: 'fitness' }, { key: 'review', label: '总结', icon: 'shield-checkmark-outline', activeIcon: 'shield-checkmark' }]; return <View style={styles.nav}>{items.map((item) => <Pressable key={item.key} onPress={() => onChange(item.key)} style={styles.navItem} accessibilityLabel={item.label}><Ionicons name={active === item.key ? item.activeIcon : item.icon} size={21} color={active === item.key ? colors.purple : colors.muted} /><Text style={[styles.navText, active === item.key && styles.navTextActive]}>{item.label}</Text></Pressable>)}</View>; }
export function EmptyState({ icon, title, detail }: { icon: IconName; title: string; detail: string }) { return <View style={styles.empty}><Ionicons name={icon} size={30} color={colors.purple} /><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyDetail}>{detail}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.bg }, content: { paddingHorizontal: 20, paddingBottom: 105 }, header: { paddingTop: 13, marginBottom: 21, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, title: { color: colors.ink, fontSize: 24, lineHeight: 30, fontWeight: '700' }, subtitle: { marginTop: 6, color: colors.muted, fontSize: 12 }, headerButton: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center' }, card: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: 16, paddingHorizontal: 14, paddingVertical: 8, ...shadow }, sectionHeader: { marginTop: 24, marginBottom: 11, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, sectionTitle: { color: '#242E41', fontSize: 15, fontWeight: '700' }, action: { color: colors.muted, fontSize: 11 }, segment: { height: 40, padding: 4, marginBottom: 22, borderRadius: 20, backgroundColor: '#EAECF3', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around' }, segmentItem: { flex: 1, height: 32, alignItems: 'center', justifyContent: 'center', borderRadius: 16 }, segmentItemActive: { backgroundColor: colors.white, ...shadow }, segmentText: { color: colors.muted, fontSize: 12 }, segmentTextActive: { color: colors.purple, fontWeight: '700' }, nav: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 78, paddingTop: 10, paddingBottom: 8, backgroundColor: 'rgba(255,255,255,0.98)', borderTopWidth: 1, borderTopColor: colors.line, flexDirection: 'row', justifyContent: 'space-around' }, navItem: { width: 65, alignItems: 'center' }, navText: { marginTop: 4, color: colors.muted, fontSize: 10 }, navTextActive: { color: colors.purple, fontWeight: '700' }, empty: { minHeight: 190, alignItems: 'center', justifyContent: 'center' }, emptyTitle: { marginTop: 12, color: colors.ink, fontSize: 14, fontWeight: '700' }, emptyDetail: { marginTop: 6, color: colors.muted, fontSize: 12 } });
