import React, { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useLifeOS } from '../store/LifeOSContext';
import { Card, colors, Header, Segment } from '../components/ui';
import type { TimelineEvent } from '../types';
const eventColors: Record<TimelineEvent['type'], string> = { task: colors.purple, workout: '#F09242', note: '#4BA9CF', journal: '#D27AB1', ai: '#5F8EF4' };
const eventIcons: Record<TimelineEvent['type'], keyof typeof Ionicons.glyphMap> = { task: 'checkbox-outline', workout: 'barbell-outline', note: 'bulb-outline', journal: 'create-outline', ai: 'sparkles-outline' };
const weekdays = ['日', '一', '二', '三', '四', '五', '六'];
const timelineDateLabel = () => { const date = new Date(); return `${date.getMonth() + 1}月${date.getDate()}日 · 星期${weekdays[date.getDay()]}`; };
export function TimelineScreen() { const { state } = useLifeOS(); const [range, setRange] = useState(0); const events = useMemo(() => [...state.timelineEvents].sort((a, b) => a.time.localeCompare(b.time)), [state.timelineEvents]); return <><Header title="时间轴" subtitle="看见今天是怎么度过的" icon="ellipsis-horizontal" /><Segment values={['今天', '本周', '本月']} active={range} onChange={setRange} /><View style={styles.dateRow}><Pressable accessibilityLabel="前一天"><Ionicons name="chevron-back" size={18} color={colors.muted} /></Pressable><Text style={styles.date}>{timelineDateLabel()}</Text><Pressable accessibilityLabel="后一天"><Ionicons name="chevron-forward" size={18} color={colors.muted} /></Pressable></View><Text style={styles.caption}>{range === 0 ? '今天的行动轨迹' : range === 1 ? '本周的行动轨迹' : '本月的行动轨迹'}</Text><View style={styles.timeline}>{events.map((event, index) => <View key={event.id} style={styles.row}><View style={styles.time}><Text style={styles.timeText}>{event.time}</Text></View><View style={styles.rail}><View style={[styles.dot, { backgroundColor: eventColors[event.type] }]} />{index < events.length - 1 && <View style={styles.line} />}</View><Card style={styles.eventCard}><View style={[styles.eventIcon, { backgroundColor: `${eventColors[event.type]}18` }]}><Ionicons name={eventIcons[event.type]} size={17} color={eventColors[event.type]} /></View><View style={{ flex: 1 }}><Text style={styles.eventTitle}>{event.title}</Text><Text style={styles.eventDetail}>{event.detail}</Text></View>{event.type === 'task' && <Text style={styles.status}>进行中</Text>}</Card></View>)}</View></>; }
const styles = StyleSheet.create({ dateRow: { marginBottom: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, date: { color: colors.ink, fontSize: 13, fontWeight: '700' }, caption: { marginBottom: 10, color: colors.muted, fontSize: 11 }, timeline: { paddingBottom: 20 }, row: { minHeight: 77, flexDirection: 'row' }, time: { width: 49, paddingTop: 15 }, timeText: { color: colors.muted, fontSize: 11 }, rail: { width: 20, alignItems: 'center', paddingTop: 17 }, dot: { width: 8, height: 8, borderRadius: 4, zIndex: 1 }, line: { position: 'absolute', top: 25, bottom: 0, width: 1, backgroundColor: colors.line }, eventCard: { flex: 1, minHeight: 66, marginBottom: 10, paddingVertical: 11, flexDirection: 'row', alignItems: 'center', gap: 10 }, eventIcon: { width: 34, height: 34, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, eventTitle: { color: '#2C374B', fontSize: 13, fontWeight: '600' }, eventDetail: { marginTop: 4, color: colors.muted, fontSize: 10 }, status: { color: colors.success, fontSize: 10 } });
